<footer class="page-footer">
    <div class="row">
        <div class="col-lg-12 d-flex d-flex justify-content-end align-items-center">
            2018 © LinkPi Studio
        </div>
    </div>
</footer>
<script src="assets/js/session.js" type="module"></script>
<script src="assets/plugins/jquery/jquery.min.js"></script>
<script src="assets/plugins/bootstrap/bootstrap.bundle.min.js"></script>
<script src="assets/plugins/vue/vue.global.prod.js"></script>
<script src="assets/plugins/pace/js/pace.min.js"></script>
<script src="assets/plugins/metismenu/js/metisMenu.min.js"></script>
<script src="assets/plugins/notifications/js/lobibox.js"></script>
<script src="assets/plugins/notifications/js/notifications.min.js"></script>
<script src="assets/plugins/notifications/js/notification-custom-script.js"></script>
<script src="assets/plugins/simplebar/js/simplebar.min.js"></script>
<script src="assets/plugins/switch/js/bootstrap-switch.js"></script>