
<?php include ("./public/footfoot.inc") ?>
<script src="assets/js/loader.js" type="module"></script>
<script src="assets/plugins/jquery/jquery.min.js"></script>
<script src="assets/plugins/bootstrap/bootstrap.bundle.min.js"></script>
<script src="assets/plugins/vue/vue.global.prod.js"></script>
<script src="assets/plugins/pace/js/pace.min.js"></script>
<script src="assets/plugins/metismenu/js/metisMenu.min.js"></script>
<script src="assets/plugins/notifications/js/lobibox.js"></script>
<script src="assets/plugins/notifications/js/notifications.min.js"></script>
<script src="assets/plugins/notifications/js/notification-custom-script.js"></script>
<script src="assets/plugins/simplebar/js/simplebar.min.js"></script>
<script src="assets/plugins/switch/js/bootstrap-switch.js"></script>
<script src="assets/plugins/vueColor/vue-color.min.js"></script>
<script src="assets/plugins/popper/popper.min.js"></script>