
<?php include ("./public/headhead.inc") ?>
<link href="assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="assets/plugins/fontawesome/css/fontawesome-all.min.css" rel="stylesheet">
<link href="assets/plugins/pace/css/pace.min.css" rel="stylesheet">
<link href="assets/plugins/notifications/css/lobibox.min.css" rel="stylesheet">
<link href="assets/plugins/metismenu/css/metisMenu.min.css" rel="stylesheet">
<link href="assets/plugins/simplebar/css/simplebar.css" rel="stylesheet">
<link href="assets/plugins/switch/css/bootstrap-switch.min.css" rel="stylesheet">
<link href="assets/plugins/confirm/css/jquery-confirm.min.css" rel="stylesheet">
<link href="assets/css/main.css" rel="stylesheet">
<link href="assets/css/theme-default.css" rel="stylesheet">
<link href="assets/css/theme-dark.css" rel="stylesheet">
<link href="assets/css/language.css" rel="stylesheet">

